CREATE TABLE IF NOT EXISTS credito
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_credito    VARCHAR(50)    NOT NULL,
    numero_nfse       VARCHAR(50)    NOT NULL,
    data_constituicao DATE           NOT NULL,
    valor_issqn       DECIMAL(15, 2) NOT NULL,
    tipo_credito      VARCHAR(50)    NOT NULL,
    simples_nacional  BOOLEAN        NOT NULL,
    aliquota          DECIMAL(5, 2)  NOT NULL,
    valor_faturado    DECIMAL(15, 2) NOT NULL,
    valor_deducao     DECIMAL(15, 2) NOT NULL,
    base_calculo      DECIMAL(15, 2) NOT NULL
);


INSERT INTO credito (numero_credito, numero_nfse, data_constituicao, valor_issqn, tipo_credito, simples_nacional, aliquota, valor_faturado, valor_deducao, base_calculo)
VALUES
('123456', '7891011', '2024-02-25', 1500.75, 'ISSQN', TRUE, 5.00, 30000.00, 5000.00, 25000.00),
('789012', '7891011', '2024-02-26', 1200.50, 'ISSQN', FALSE, 4.50, 25000.00, 4000.00, 21000.00),
('654321', '1122334', '2024-01-15', 800.50, 'Outros', TRUE, 3.50, 20000.00, 3000.00, 17000.00)
ON CONFLICT (id) DO NOTHING;
